server:
  port: 8082
#  servlet:
#    context-path: /test 

#spring:
 # thymeleaf:
  #  prefix: classpath:/templates
   # suffix: .html

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

cupsize: this-is-my-test-data
age: 12

girl: 
   name: cunsen===
   age: 30
   address: this is for dev